[project]
name = "lab2"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "avro>=1.12.0",
    "numpy>=2.2.2",
    "pyarrow>=19.0.0",
    "pyright>=1.1.393",
    "ruff>=0.9.4",
]
